version: "3"
services:
  assesment:
    image: assesment
    restart: always
    ports:
      - 7000:7000
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: Epam@123
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: assesmentproject
      MYSQL_ROOT_PASSWORD: Epam@123
#version: "3"
#services:
#  assesment:
#    image: assesment
#    restart: always
#    ports:
#      - 7000:7000






